% !TeX program = pdfLaTeX
\documentclass[smallextended]{svjour3}       % onecolumn (second format)
%\documentclass[twocolumn]{svjour3}          % twocolumn
%
\smartqed  % flush right qed marks, e.g. at end of proof
%
\usepackage{amsmath}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}

\usepackage[hyphens]{url} % not crucial - just used below for the URL
\usepackage{hyperref}

%
% \usepackage{mathptmx}      % use Times fonts if available on your TeX system
%
% insert here the call for the packages your document requires
%\usepackage{latexsym}
% etc.
%
% please place your own definitions here and don't use \def but
% \newcommand{}{}
%
% Insert the name of "your journal" with
% \journalname{myjournal}
%

%% load any required packages here


% Pandoc syntax highlighting
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}

% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% From pandoc table feature
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}

% Pandoc citation processing
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
% for Pandoc 2.8 to 2.10.1
\newenvironment{cslreferences}%
  {}%
  {\par}
% For Pandoc 2.11+
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\begin{document}


\title{My Example Computed Manuscript }
 \subtitle{Created in Rmarkdown} 

    \titlerunning{Example computed manuscript}

\author{  Jeffrey M. Perkel \and  }


\institute{
        Jeffrey M. Perkel \at
     Springer Nature, 1 New York Plaza, New York, NY \\
     \email{\href{mailto:jeffrey.perkel@nature.com}{\nolinkurl{jeffrey.perkel@nature.com}}}  %  \\
%             \emph{Present address:} of F. Author  %  if needed
    \and
    }

\date{Received: date / Accepted: date}
% The correct dates will be entered by the editor


\maketitle

\begin{abstract}
A mock computed manuscript created in RStudio using \{Rmarkdown\}. The \{Bookdown\} and \{Rticles\} packages were used to output the text in Springer Nature's desired manuscript format.
\\
\keywords{
    }


\end{abstract}


\def\spacingset#1{\renewcommand{\baselinestretch}%
{#1}\small\normalsize} \spacingset{1}


\hypertarget{intro}{%
\section{Introduction}\label{intro}}

This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see \url{http://rmarkdown.rstudio.com}.

Here we'll add some references from Zotero (Perkel 2020): (Fisch et al. 2015; Argelaguet et al. 2021; Lê Cao et al. 2021).

Markdown documents can include inline equations written in \LaTeX, such as \(F = ma\). Here is an equation on its own line:

\[a^2 + b^2 = c^2\]

\hypertarget{results}{%
\section{Results}\label{results}}

\hypertarget{sec:1}{%
\subsection{Inline computation}\label{sec:1}}

One `killer feature' of computed manuscripts is the ability to compute and insert values into the text rather than requiring authors to input them manually. That circumvents the possibility that the author will enter an incorrect number, or forget to update them should new data arise.

For instance, imagine we are analyzing data from a clinical trial. We have grouped subjects in three bins and measured their weights.

\begin{table}

\caption{\label{tab:subject-weights}Original subject data}
\centering
\begin{tabular}[t]{rlrlrlrlrlr}
\toprule
ID & class & wt & | & ID & class & wt & | & ID & class & wt\\
\midrule
1 & Group 2 & 134 & | & 34 & Group 1 & 183 & | & 67 & Group 3 & 226\\
2 & Group 1 & 95 & | & 35 & Group 1 & 234 & | & 68 & Group 1 & 124\\
3 & Group 3 & 160 & | & 36 & Group 3 & 194 & | & 69 & Group 2 & 75\\
4 & Group 2 & 269 & | & 37 & Group 2 & 106 & | & 70 & Group 2 & 178\\
5 & Group 1 & 204 & | & 38 & Group 2 & 247 & | & 71 & Group 1 & 212\\
\addlinespace
6 & Group 2 & 145 & | & 39 & Group 2 & 120 & | & 72 & Group 3 & 77\\
7 & Group 1 & 167 & | & 40 & Group 2 & 90 & | & 73 & Group 3 & 146\\
8 & Group 3 & 271 & | & 41 & Group 1 & 206 & | & 74 & Group 1 & 263\\
9 & Group 1 & 107 & | & 42 & Group 2 & 263 & | & 75 & Group 2 & 147\\
10 & Group 1 & 115 & | & 43 & Group 2 & 208 & | & 76 & Group 3 & 236\\
\addlinespace
11 & Group 2 & 236 & | & 44 & Group 3 & 134 & | & 77 & Group 1 & 79\\
12 & Group 1 & 80 & | & 45 & Group 1 & 154 & | & 78 & Group 2 & 293\\
13 & Group 3 & 208 & | & 46 & Group 1 & 143 & | & 79 & Group 1 & 211\\
14 & Group 2 & 189 & | & 47 & Group 2 & 87 & | & 80 & Group 2 & 161\\
15 & Group 3 & 215 & | & 48 & Group 1 & 112 & | & 81 & Group 2 & 296\\
\addlinespace
16 & Group 2 & 206 & | & 49 & Group 1 & 84 & | & 82 & Group 2 & 89\\
17 & Group 3 & 273 & | & 50 & Group 1 & 132 & | & 83 & Group 3 & 204\\
18 & Group 3 & 240 & | & 51 & Group 1 & 172 & | & 84 & Group 2 & 224\\
19 & Group 1 & 171 & | & 52 & Group 3 & 241 & | & 85 & Group 1 & 259\\
20 & Group 1 & 104 & | & 53 & Group 3 & 152 & | & 86 & Group 2 & 165\\
\addlinespace
21 & Group 1 & 241 & | & 54 & Group 3 & 244 & | & 87 & Group 1 & 284\\
22 & Group 2 & 260 & | & 55 & Group 1 & 189 & | & 88 & Group 2 & 103\\
23 & Group 3 & 134 & | & 56 & Group 1 & 89 & | & 89 & Group 3 & 218\\
24 & Group 3 & 237 & | & 57 & Group 3 & 198 & | & 90 & Group 2 & 207\\
25 & Group 1 & 214 & | & 58 & Group 1 & 178 & | & 91 & Group 1 & 252\\
\addlinespace
26 & Group 1 & 114 & | & 59 & Group 1 & 110 & | & 92 & Group 1 & 206\\
27 & Group 1 & 102 & | & 60 & Group 2 & 127 & | & 93 & Group 2 & 79\\
28 & Group 2 & 272 & | & 61 & Group 2 & 160 & | & 94 & Group 1 & 290\\
29 & Group 3 & 201 & | & 62 & Group 3 & 210 & | & 95 & Group 2 & 199\\
30 & Group 1 & 282 & | & 63 & Group 1 & 116 & | & 96 & Group 1 & 181\\
\addlinespace
31 & Group 2 & 165 & | & 64 & Group 3 & 158 & | & 97 & Group 1 & 202\\
32 & Group 2 & 238 & | & 65 & Group 1 & 158 & | & 98 & Group 1 & 213\\
33 & Group 3 & 252 & | & 66 & Group 1 & 120 & | & 99 & Group 3 & 176\\
\bottomrule
\end{tabular}
\end{table}

Rather than analyzing those data programmatically and then copying them into our manuscript, we can use the programming language \texttt{R} to do that in the manuscript itself. For instance, to calculate the circumference and area of a circle with radius \emph{r} = 10, you could write ``A = \texttt{\textasciigrave{}r\ pi\ *\ r\^{}2\textasciigrave{}}'' and "C = \texttt{\textasciigrave{}r\ 2\ *\ pi\ *\ r\textasciigrave{}}. Those give A = 314.159 and C = 62.832.

We have \textbf{99} subjects in our study (Table \ref{tab:subject-weights}). The average weight is \textbf{180.76} (range: \textbf{75}-\textbf{296}). We have \textbf{42} subjects in Group 1, \textbf{32} subjects in Group 2, and \textbf{25} in Group 3. (The numbers in \textbf{bold face type} are computed values.)

Now suppose we get another tranche of data:

\begin{table}

\caption{\label{tab:new-data}New subject data}
\centering
\begin{tabular}[t]{rlrlrlrlrlr}
\toprule
ID & class & wt & | & ID & class & wt & | & ID & class & wt\\
\midrule
1 & Group 3 & 256 & | & 21 & Group 3 & 104 & | & 41 & Group 3 & 144\\
2 & Group 3 & 296 & | & 22 & Group 2 & 227 & | & 42 & Group 3 & 105\\
3 & Group 3 & 291 & | & 23 & Group 2 & 144 & | & 43 & Group 3 & 89\\
4 & Group 2 & 258 & | & 24 & Group 3 & 250 & | & 44 & Group 3 & 112\\
5 & Group 1 & 78 & | & 25 & Group 2 & 194 & | & 45 & Group 3 & 88\\
\addlinespace
6 & Group 1 & 238 & | & 26 & Group 2 & 90 & | & 46 & Group 1 & 299\\
7 & Group 1 & 121 & | & 27 & Group 1 & 75 & | & 47 & Group 2 & 85\\
8 & Group 3 & 96 & | & 28 & Group 1 & 213 & | & 48 & Group 1 & 292\\
9 & Group 2 & 120 & | & 29 & Group 1 & 122 & | & 49 & Group 3 & 267\\
10 & Group 1 & 273 & | & 30 & Group 2 & 178 & | & 50 & Group 3 & 159\\
\addlinespace
11 & Group 3 & 100 & | & 31 & Group 2 & 155 & | & 51 & Group 1 & 147\\
12 & Group 1 & 106 & | & 32 & Group 3 & 249 & | & 52 & Group 1 & 96\\
13 & Group 3 & 121 & | & 33 & Group 2 & 292 & | & 53 & Group 3 & 172\\
14 & Group 3 & 185 & | & 34 & Group 1 & 294 & | & 54 & Group 1 & 299\\
15 & Group 3 & 223 & | & 35 & Group 3 & 264 & | & 55 & Group 3 & 189\\
\addlinespace
16 & Group 3 & 205 & | & 36 & Group 3 & 133 & | & 56 & Group 3 & 215\\
17 & Group 1 & 129 & | & 37 & Group 2 & 183 & | & 57 & Group 2 & 154\\
18 & Group 3 & 258 & | & 38 & Group 1 & 91 & | & 58 & Group 3 & 291\\
19 & Group 2 & 130 & | & 39 & Group 3 & 183 & | & 59 & Group 1 & 204\\
20 & Group 1 & 272 & | & 40 & Group 1 & 141 & | & 60 & Group 2 & 293\\
\bottomrule
\end{tabular}
\end{table}

There are \textbf{60} subjects in this new dataset (Table \ref{tab:new-data}). Their average weight is \textbf{183.97} (range: \textbf{75}-\textbf{299}).

Combining the two datasets, we have a total of \textbf{159} subjects. The revised average weight is \textbf{181.97} (range: \textbf{75}-\textbf{299}). We now have \textbf{61} subjects in Group 1, \textbf{46} subjects in Group 2, and \textbf{52} in Group 3.

\hypertarget{sec:2}{%
\subsection{Plotting the data}\label{sec:2}}

As Rmarkdown documents can do anything R can do, we can also create and include figures. Here we plot boxplots of our clinical trial data. The data are shown in Figure \ref{fig:plot-data}. Note that this figure number (as well as the table numbers above) are automatically generated.

\begin{figure}
\centering
\includegraphics{SN_templates_files/figure-latex/plot-data-1.pdf}
\caption{\label{fig:plot-data}Weight distribution of clinical trial subjects}
\end{figure}

\hypertarget{methods}{%
\section{Methods}\label{methods}}

The following code was used in section \ref{sec:1} to create the original clinical trial data:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create a mock dataset}
\NormalTok{n\_subjs }\OtherTok{\textless{}{-}} \DecValTok{99}
\NormalTok{subjID }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\NormalTok{n\_subjs}

\CommentTok{\# generate 99 random \#s between 1 and 10}
\NormalTok{tmp }\OtherTok{\textless{}{-}} \FunctionTok{floor}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n\_subjs, }\AttributeTok{min =} \DecValTok{1}\NormalTok{, }\AttributeTok{max =} \DecValTok{10}\NormalTok{))}
\CommentTok{\# assign those numbers to any of 3 subject groups}
\NormalTok{fn }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{ }
  \ControlFlowTok{if}\NormalTok{ (x }\SpecialCharTok{\textgreater{}=} \DecValTok{7}\NormalTok{) }\StringTok{\textquotesingle{}Group 1\textquotesingle{}} 
  \ControlFlowTok{else} \ControlFlowTok{if}\NormalTok{ (x }\SpecialCharTok{\textgreater{}=} \DecValTok{4}\NormalTok{) }\StringTok{\textquotesingle{}Group 2\textquotesingle{}} 
  \ControlFlowTok{else} \StringTok{\textquotesingle{}Group 3\textquotesingle{}} 
\NormalTok{\}}
\NormalTok{subj\_class }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(tmp, fn)}

\CommentTok{\# pick random weights between 75 and 300}
\NormalTok{wts }\OtherTok{\textless{}{-}} \FunctionTok{floor}\NormalTok{(}\FunctionTok{runif}\NormalTok{(n\_subjs, }\AttributeTok{min =} \DecValTok{75}\NormalTok{, }\AttributeTok{max =} \DecValTok{300}\NormalTok{))}
\CommentTok{\# combine the data into a table}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{ID =}\NormalTok{ subjID, }\AttributeTok{class =}\NormalTok{ subj\_class, }\AttributeTok{wt =}\NormalTok{ wts)}

\CommentTok{\# display the table, splitting the 99 rows into 3 cols wide}
\NormalTok{tmp }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(df[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{33}\NormalTok{,], }\FunctionTok{rep}\NormalTok{(}\StringTok{\textquotesingle{}|\textquotesingle{}}\NormalTok{, }\DecValTok{33}\NormalTok{), }
\NormalTok{             df[}\DecValTok{34}\SpecialCharTok{:}\DecValTok{66}\NormalTok{,], }\FunctionTok{rep}\NormalTok{(}\StringTok{\textquotesingle{}|\textquotesingle{}}\NormalTok{, }\DecValTok{33}\NormalTok{), }
\NormalTok{             df[}\DecValTok{67}\SpecialCharTok{:}\DecValTok{99}\NormalTok{,])}
\FunctionTok{names}\NormalTok{(tmp) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}ID\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}class\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}wt\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}|\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ID\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}class\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}wt\textquotesingle{}}\NormalTok{, }
                \StringTok{\textquotesingle{}|\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}ID\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}class\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}wt\textquotesingle{}}\NormalTok{)}
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(tmp, }\AttributeTok{format =} \StringTok{\textquotesingle{}latex\textquotesingle{}}\NormalTok{, }\AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{, }
             \AttributeTok{caption =} \StringTok{"Original subject data"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The following code was used in section \ref{sec:2} to plot the data:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{final\_data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ class, }\AttributeTok{y =}\NormalTok{ wt, }\AttributeTok{color =}\NormalTok{ class)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_jitter}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.25}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{""}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Weight"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\hypertarget{ref-argelaguet_computational_2021}{}%
Argelaguet, Ricard, Anna S. E. Cuomo, Oliver Stegle, and John C. Marioni. 2021. {``Computational Principles and Challenges in Single-Cell Data Integration.''} \emph{Nature Biotechnology}, May, 1--14. \url{https://doi.org/10.1038/s41587-021-00895-7}.

\leavevmode\hypertarget{ref-fisch_omics_2015}{}%
Fisch, K. M., T. Meissner, L. Gioia, J.-C. Ducom, T. M. Carland, S. Loguercio, and A. I. Su. 2015. {``Omics {Pipe}: A Community-Based Framework for Reproducible Multi-Omics Data Analysis.''} \emph{Bioinformatics} 31 (11): 1724--28. \url{https://doi.org/10.1093/bioinformatics/btv061}.

\leavevmode\hypertarget{ref-le_cao_community-wide_2021}{}%
Lê Cao, Kim-Anh, Al J. Abadi, Emily F. Davis-Marcisak, Lauren Hsu, Arshi Arora, Alexis Coullomb, Atul Deshpande, et al. 2021. {``Community-Wide Hackathons to Identify Central Themes in Single-Cell Multi-Omics.''} \emph{Genome Biology} 22 (1): 220. \url{https://doi.org/10.1186/s13059-021-02433-9}.

\leavevmode\hypertarget{ref-perkel2020}{}%
Perkel, Jeffrey M. 2020. {``Streamline Your Writing {{}} and Collaborations {{}} with These Reference Managers.''} \emph{Nature} 585 (7823): 149--50. \url{https://doi.org/10.1038/d41586-020-02491-2}.

\end{CSLReferences}


\bibliographystyle{spbasic}
\bibliography{bibliography.bib}


\end{document}
